### ISSUE TITLE
22 compile errors: Array types are now written with the brackets around the element type and other errors

### ISSUE THREAD

**Issue by mortenholmgaard** [mythz/swift-linq-examples#3]
I get 22 errors when cloning the project, do to changes in the swift language.

**Comment by mortenholmgaard** [comment]
Any one?

**Comment by mythz** [comment]
I'll look at updating it after Swift 1.2 is out of beta.

**Comment by mortenholmgaard** [comment]
When will you look at this?

**Comment by mythz** [comment]
As I said before, after Swift 1.2 is out of beta and I have time. If you want it earlier send a PR.
