### ISSUE TITLE
Anyone maintaining a non-extension based comparison?

### ISSUE THREAD

**Issue by patniemeyer** [mythz/swift-linq-examples#7]
I think it would be very helpful for the Swift community to have a side by side comparison with LINQ that didn't rely on the extensions to try to bridge missing features.  While the extensions are totally reasonable in real code of course they kind of mask the deficiencies of Swift and the core libs as a language and it would be nice to shine a spotlight on those gaps while the language is evolving.

**Comment by mythz** [comment]
We're not planning to maintain parallel examples like this. The examples are meant to show the expressivity of each language, not just what features are built into the standard library. 

BTW the examples have now been upgraded to Swift 3.0

**Comment by patniemeyer** [comment]
I understand, but to play devil's advocate: One could completely implement C# in Swift or vice versa if you went far enough.  It's not really comparing the native expressiveness of the core languages if you must use elaborate or incomplete libraries to fill the gap.
